services:
  - type: web
    name: rock-arena
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
